# Generated by Django 5.2.5 on 2025-08-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(default='2000-1-1', verbose_name='fecha_nacimiento'),
        ),
    ]
